server:
  port: 8888
  
spring:
  application:
    name: HPE SETTLE Development
  freemarker:
    contentType: text/html
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
    templateEncoding: UTF-8
    cache: true
    
logging:
  config: classpath:log/logback.xml
  #path: /log/logs
  #file: demo.log
  #level: #这里可以通过包来划分每个包中的日志级别，root为根，默认root为info级别
  #  root: debug
  #  com.hpe.settle: debug
management:
  security:
    enabled: false